gamemode=survival
player-idle-timeout=30
max-players=20
online-mode=true
level-seed=123456789
level-type=DEFAULT
content-log-file-enabled=true
allow-cheats=false
player-movement-score-threshold=20
server-port6=0
max-threads=8
difficulty=normal
server-name=survival-world
server-authoritative-movement=server-auth
enable-lan-visibility=false
server-port=20000
correct-player-movement=true
enable-command-blocking=false
enable-ipv6=false
ipv6-port=0
default-player-permission-level=member
player-movement-distance-threshold=0.3
player-movement-duration-threshold-in-ms=500
server-ip=
level-name=survival
enable-scripts=false
max-world-size=10000
